version: "3.8"

services:
    uvdesk:
        container_name: uvdesk_container
        # image: {IMAGE_NAME}:latest
        build: ./uv_desk
        restart: unless-stopped
        tty: true
        volumes:
            - ./uv_desk:/var/www/uvdesk
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        networks:
            - nginx_network
            - mysql_network
        depends_on: 
            - mysql
        command: service cron start

    mysql:
        container_name: uvdesk_db
        image: mysql:8.0
        # command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
    
    adminer:
        container_name: uvdesk_adminer
        image: adminer
        restart: unless-stopped
        networks:
            - mysql_network
        
    nginx:
        container_name: uvdesk_nginx
        image: nginx:1.18
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - nginx_network
        depends_on:
            - uvdesk
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
    mysql_network:
        driver: bridge
    nginx_network:
        driver: bridge

volumes:
    uvdesk_volume: